# Generated by Django 3.2.4 on 2021-06-09 22:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superheroe',
            name='iden',
        ),
        migrations.AlterField(
            model_name='superheroe',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
