# Generated by Django 3.2.4 on 2021-06-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_auto_20210610_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroe',
            name='ide',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superheroe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
