# Generated by Django 3.2.4 on 2021-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0003_auto_20210610_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superheroe',
            name='ide',
        ),
        migrations.AlterField(
            model_name='superheroe',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
